.Dd January 29, 2025
.Dt L1LIGHT 1
.Os
.Sh NAME
.Nm l1light
.Nd set device brightness using login1 interface
.Sh SYNOPSIS
.Bk -words
.Nm l1light
.Op Fl t Ar subsys Ns / Ns Ar device
.Op Fl rlhv
.Op Ar val
.Ek
.Sh DESCRIPTION
.Nm
sets the brightness on a device to the percentage specified as an integer in
.Ar val
using
.Xr org.freedesktop.login1 5 Ns .
The brightness percentage is printed if
.Ar val
is not specified.
.Pp
If
.Ar val
starts with
.Ql +
or
.Ql \- Ns ,
the specified percentage is added to the brightness value. If
.Ql toggle
is specified, the brightness is set as 0 or 1.
.Pp
.Nm
is mainly used to set screen brightness in GUI sessions in cases where it
cannot be done as a regular user without modifying other configuration.
.Pp
The options that can be specified on command line are written below.
.Bl -tag
.It Fl t Ar subsys Ns / Ns Ar device
Set or print brightness on
.Ar device
in
.Ar subsys Ns .
If
.Ar device
is specified as
.Ql auto Ns ,
a device assigned to the seat where
.Nm
is run will be used (see
.Xr sd\-login 3 Ns ).
The default value is
.Ql backlight/auto Ns .
.It Fl r
Set or print raw value.
.It Fl l
Print available target devices.
.It Fl h
Print help.
.It Fl V
Print version.
.El
.Sh ENVIRONMENT
.Bl -tag
.It Ev XDG_SEAT
Seat where device is detected if not specified.
.It Ev XDG_SESSION_ID
Session where brightness is set.
.El
.Sh FILES
.Bl -tag
.It Pa /sys/class/*/*/backlight
Device brightness value.
.It Pa /sys/class/*/*/max_backlight
Maximum brightness value.
.Sh EXIT STATUS
The exit status is 0 if no error has occured.
.El
.Sh SEE ALSO
.Xr sd\-login 3 ,
.Xr org.freedesktop.login1 5
